---
  - name: Install bash-completion
    become: true
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - bash-completion

  - name: Make the bash-completion persistent
    shell: "{{ item }}"
    with_items:
      - echo "source <(kubectl completion bash)" >> ~/.bashrc