  - name: containerd prerequisites
    become: true
    command: "{{ item }}"
    with_items:
     - modprobe overlay
     - modprobe br_netfilter
  
  - name: containerd
    shell: |
      cat <<EOF | sudo tee /etc/modules-load.d/containerd.conf
      overlay 
      br_netfilter 
      EOF

  - name: Setup required sysctl params, these persist across reboots
    shell: |
      cat <<EOF | sudo tee /etc/sysctl.d/99-kubernetes-cri.conf
      net.bridge.bridge-nf-call-iptables  = 1
      net.ipv4.ip_forward                 = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      EOF

  - name: Apply sysctl params without reboot
    become: true
    command: sysctl --system

  - name: install containerd
    become: true
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - containerd

  - name: Configure containerd
    become: true
    shell: "{{ item }}"
    with_items:
     - mkdir -p /etc/containerd
     - containerd config default | sudo tee /etc/containerd/config.toml
  
  - name: To use the systemd cgroup driver in /etc/containerd/config.toml with runc, set
    become: true
    lineinfile:
      path: /etc/containerd/config.toml
      insertbefore: 'plugins."io.containerd.grpc.v1.cri".cni'
      line: "{{ item }}"
    with_items: 
      - '          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]'
      - '           SystemdCgroup = true'

  - name: restart containerd
    become: true
    command: systemctl restart containerd